### PR TITLE
Add turtlebot_navigation to turtlebot_gazebo depends

### PR DESCRIPTION
**Pull request by jspricke**
gmapping_demo.launch depends on it.

### CODE REVIEW

**Comment by jspricke** [comment]
Please remember to merge this into indigo as well.

**Comment by jspricke** [comment]
The other option would be to move the file to TURTLEBOT_navigation.

**Comment by jihoonl** [comment]
Thanks.

**Comment by jihoonl** [comment]
Cherry-picked on hydro-devel and indigo

**Pull request merged**
