### PR TITLE
turtlebot_stdr v0.1

### PR DESCRIPTION
**Pull request by mehditlili**
First working version using STDR instead of stage_ros.

### CODE REVIEW

**Comment by jihoonl** [comment]
Nice work @mehditlili! Looks nice.

**Comment by jihoonl** [comment]
I would like to apply some changes. Could you update the PR with the following changes?
- CMakeLists.txt cleanup.
  - Remove all unncessary comments.
  - Add rules to install directories like launch, rviz, and maps.
- Use `move_base.launch.xml` and `amcl.launch.xml` in turtlebot_navigation package. Or Does it need to keep the copy in the package?

Thanks!

**Comment by mehditlili** [comment]
Done. But please also check my pull request for turtlebot_apps before merging this one. They depend on each other.

**Comment by jihoonl** [comment]
Great. Thanks.

**Pull request merged**
