### PR TITLE
Sync the stage simulation with the real turtlebot configuration

### PR DESCRIPTION
**Pull request by stonier**
Also a fair bit of cleanup, see #21.

### CODE REVIEW

**Comment by stonier** [comment]
@jihoonl can you have a look at this when you have time?

**Comment by jihoonl** [comment]
turtlebot_stage package was intended to experiment navigation approaches. That was why elastic band configuration and virtual sensor enabled version of roslaunch.

Do you have any suggestion to keep these experiments? 
elastic band configuration could go into turtlebot_navigation package. 

But I am not sure about where virtual sensor should go. It is enoughly interesting idea which we should experiment in the future. I would like to keep this somewhere as a reference.

**Comment by stonier** [comment]
This is a released package so the default simulation that stage provides should be simulating the actual turtlebot configuration (not an experiment).

I don't mind the idea of providing extra args or launchers for showing people how they can get started  with other planners like the eband planner, but...
- no broken or black magic dependencies (it's a release).
- someone willing to maintain and is an expert who can impart the correct information (don't want to be teaching bad habits) in comments and tutorials.

The second point is very important - we already know how difficult it is following confusing/out of date information and I don't see anyone stepping up to do these things right now so I'm more inclined to drop them than be a possible source of erroneous information.

**Comment by stonier** [comment]
> It is enoughly interesting idea which we should experiment in the future. I would like to keep this somewhere as a reference.

I agree. Anywhere outside of a public release is fine.

**Comment by stonier** [comment]
Also added a commit which fixes the stage 'box' for the robot so it doesn't accidentally collide outside of the costmap defined circular robot radius.

**Comment by jihoonl** [comment]
Ok. All make sense. Merging it now. And I have forked the repository into my account to keep the snapshot.

Or would it be better to keep them in a separate branch?

**Comment by stonier** [comment]
An experimental branch here would be fine. The only thing I would like to stress here is that the release branch (the first one a user sees) should be free of surprises and always working out of the box for the user.

**Comment by bit-pirate** [comment]
Delete branch?

**Comment by jihoonl** [comment]
deleted.

**Pull request merged**
