### PR TITLE
Stage launch use env variables

### PR DESCRIPTION
**Pull request by AlexReimann**
turtlebot_stage launcher now uses environment variables for setting map and world file

### CODE REVIEW

**Comment by jihoonl** [comment]
Wait. env-hook directory should be under turtlebot_stage. Also we might want to install it too?

**Comment by jihoonl** [comment]
Would you make these changes?

**Comment by AlexReimann** [comment]
What do you mean with installing it?

**Comment by stonier** [comment]
@jihoonl I believe the catkin macro setting up the environment hooks automatically sets up install rules.

**Pull request merged**
