### PR TITLE
fixed map and costmap misalignement due to wrong frame_id

### PR DESCRIPTION
**Pull request by mehditlili**
The map published by STDR had "map" as frame ID whereas I am using "world" as global frame_id. This causes a misalignment between static_map and global_costmap in RVIZ. The only way to fix this was to run a parallel map server that publishes the same static map to a different topic (i.e /new_map) but with a frame_id "world" and choose it in RVIZ instead of "/map".
If my description was not clear, I can show you directly on my computer.

### CODE REVIEW

**Comment by mehditlili** [comment]
topic renamed to rviz_map. An alternative like you suggested would be to remap STDR map to unused_map and just use the map from map_server.

**Comment by mehditlili** [comment]
I made a pull request to change the frame-id in stdr from map to world. I will let you know when they merge it so that you merge my last changes in turtlebot_stdr.

**Comment by stonier** [comment]
@mehditlili : got a link to that stdr pull request?

**Comment by mehditlili** [comment]
Here : https://github.com/stdr-simulator-ros-pkg/stdr_simulator/pull/164

**Comment by jihoonl** [comment]
Any progress on this?

**Pull request merged**
