### PR TITLE
Added env-hooks and changed fixed frame for rviz

### PR DESCRIPTION
**Pull request by mehditlili**

### CODE REVIEW

**Comment by stonier** [comment]
Did you get a chance to see what happened with the unsynchronised static map obstacle problem after setting turtlebot_navigation's global costmap frame from `map` -> `world`?

**Comment by mehditlili** [comment]
It actually fixed the global costmap to the static plan so problem solved.

**Comment by mehditlili** [comment]
Local costmap working, it was because the min max height was limited between 0.25 and 0.35, I have set it to 0~2.

**Comment by jihoonl** [comment]
:+1:

**Pull request merged**
